---
- hosts: webservers
  tasks:
  - name: create and start a nginx container
    docker_container:
      name: nginx-container
      image: nginx
      state: started
      recreate: yes
      ports:
        - 80:80
    tags: create
  - name: remove nginx container
    docker_container:
      name: nginx-container
      image: nginx
      state: absent
      recreate: yes
      ports:
        - 80:80
    tags: delete
