---
- hosts: localhost
  tasks:
  - name: Install boto3 for Ansible Lookup Plugin to work
    pip:
      name: boto3
    tags: create	  
  - name: Install mysql packages
    docker_container:
      name: mysql-container
      image: mysql:5.7
      state: started
      recreate: yes
      ports:
        - 3306:3306
      volumes:
        - /var/lib/mysql
      env:
        "MYSQL_ROOT_PASSWORD": "{{ lookup('aws_secret', 'dev/app/mysql') }}"
    tags: create
  - name: Remove mysql packages
    docker_container:
      name: mysql-container
      image: mysql:5.7
      state: absent
      recreate: yes
      ports:
        - 3306:3306
      volumes:
        - /var/lib/mysql
      env:
        "MYSQL_ROOT_PASSWORD": "{{ lookup('aws_secret', 'dev/app/mysql') }}"
    tags: remove

