---
- hosts: webservers
  vars_files:
    - mysql_pass.yml
  tasks:
  - name: Install mysql packages
    docker_container:
      name: mysql-container
      image: mysql:5.7
      state: started
      recreate: yes
      ports:
        - 3306:3306
      volumes:
        - /var/lib/mysql
      env:
        MYSQL_ROOT_PASSWORD: "{{ db_password }}"
        MYSQL_DATABASE: employeedb
        MYSQL_USER: naresh
        MYSQL_PASSWORD: "{{ db_password }}"
    tags: create
  - name: Removing mysql packages
    docker_container:
      name: mysql-container
      image: mysql:5.7
      state: absent
      recreate: yes
      ports:
        - 3306:3306
      volumes:
        - /var/lib/mysql
      env:
        MYSQL_ROOT_PASSWORD: "{{ db_password }}"
        MYSQL_DATABASE: employeedb
        MYSQL_USER: naresh
        MYSQL_PASSWORD: "{{ db_password }}"
    tags: remove
