---
- hosts: test
  tasks:
  - name: find operating system
    debug:
      msg="{{ ansible_distribution }}"
  - name: install java in Linux
    yum:
      name: java-1.8.0-openjdk
      state: present
      update_cache: yes
    when: ansible_distribution == "Amazon"
  - name: install java in ubuntu
    apt:
      name: openjdk-8-jre-headless
      state: present
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
