---
- hosts: webservers
  tasks:
    - name: Install Apache Webserer on Amazon Linux/Amazon Linux2/RHEL
      yum:
        name: httpd
        state: present
      when: ansible_facts['distribution'] == "RedHat" 
    - name: Install Apache Webserver on Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
