---
- hosts: installations
  vars:
    tomcat_download_url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.46/bin/apache-tomcat-9.0.46.tar.gz
    tomcat_download_directory: /opt
    tomcat_version: 9.0.46
  tasks:
  - name: Check if java rpm is already installed or not
    yum:
      list: java-1.8.0-openjdk
    register: check_java_existence
  - name : Install java
    yum:
      name: java-1.8.0-openjdk
      state: present
    when: check_java_existence.results | selectattr("yumstate", "match", "installed") | list | length == 0
  - name: Print variables
    debug:
      msg: "{{ tomcat_download_url }}"
  - name: Print variables
    debug:
      msg: "{{ tomcat_download_url }}"
  - name: Check Tomcat already exists or not
    stat:
      path: "{{ tomcat_download_directory }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
    register: check_tomcat_existence
  - name: Print tomcat tar file exists or not
    debug:
      msg: "{{ check_tomcat_existence }}"
  - name: Download Apache Tomcat 9
    get_url:
      url: "{{ tomcat_download_url }}"
      dest: "{{ tomcat_download_directory }}"
      mode: '0777'
    when: not check_tomcat_existence.stat.exists
  - name: unarchive Apache tomcat
    unarchive:
      src: "{{ tomcat_download_directory }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
      dest: "{{ tomcat_download_directory }}"
      remote_src: yes
  - name: Create Tomcat user and Group
    user:
      name: tomcat
      comment: user for tomcat
  - name: Change owner ship for tomcat
    file:
      path: /opt/apache-tomcat-{{ tomcat_version }}
      state: directory
      recurse: yes
      owner: tomcat
      group: tomcat
      mode: '0755'
  - name : Tomcat template
    template:
      src: tomcat.service.j2
      dest: ./tomcat.service
  - name: Copy Tomcat service from local to remote
    copy:
      src: ./tomcat.service
      dest: /etc/systemd/system/
      mode: 0755
      remote_src: yes
  - name: just force systemd to reread configs (2.4 and above)
    systemd:
      daemon_reload: yes
  - name: enable tomcat startup
    service:
      name: tomcat
      state: restarted
